/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'news-tags': NewsTag;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'news-tags': NewsTagsSelect<false> | NewsTagsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    home: Home;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * The project name displayed on project cards.
   */
  title: string;
  /**
   * Short summary displayed on project cards and featured project listings.
   */
  shortDescription: string;
  /**
   * Where this project card links. Use an internal path for now, or an external URL when needed.
   */
  href: string;
  /**
   * Whether this project link opens in a new browser tab.
   */
  newTab?: boolean | null;
  /**
   * Optional image shown on the project card. A neutral placeholder appears when empty.
   */
  image?: (number | null) | Media;
  /**
   * Optional alt text override. Leave empty to use the media alt text.
   */
  imageAlt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-tags".
 */
export interface NewsTag {
  id: number;
  /**
   * The tag label displayed on news cards and articles.
   */
  name: string;
  /**
   * Optional badge color. Leave blank to use the default badge color.
   */
  badgeColor?: ('evergreen' | 'sky' | 'rose' | 'amber') | null;
  /**
   * Generated from the tag name and used in news tag URLs.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'news-tags';
        value: number | NewsTag;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  href?: T;
  newTab?: T;
  image?: T;
  imageAlt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-tags_select".
 */
export interface NewsTagsSelect<T extends boolean = true> {
  name?: T;
  badgeColor?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Controls the brand link, primary navigation and contact action in the site header.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Links are rendered left to right in the desktop primary navigation.
   */
  navItems: {
    /**
     * The text to display for the navigation item.
     */
    label: string;
    /**
     * The URL or path the navigation item links to. Use a relative path, anchor or full http(s), mailto or tel URL.
     */
    href: string;
    /**
     * Whether the link should open in a new tab.
     */
    newTab?: boolean | null;
    id?: string | null;
  }[];
  contactLink: {
    /**
     * Whether to show the contact link in the header.
     */
    enabled?: boolean | null;
    /**
     * The text to display for the contact link.
     */
    label: string;
    /**
     * The URL or path the contact link points to. Use a relative path, anchor or full http(s), mailto or tel URL.
     */
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls footer navigation, acknowledgement text, social links and newsletter copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Heading for the first footer navigation group.
   */
  primaryNavigationTitle: string;
  /**
   * Links in the first footer navigation group.
   */
  primaryNavigationItems: {
    /**
     * The text to display for the link.
     */
    label: string;
    /**
     * The URL or path the link points to. Use a relative path, anchor or full http(s), mailto or tel URL.
     */
    href: string;
    /**
     * Whether the link should open in a new tab.
     */
    newTab?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Heading for the project navigation group.
   */
  projectNavigationTitle: string;
  /**
   * Project links shown across two footer columns.
   */
  projectNavigationItems: {
    /**
     * The text to display for the link.
     */
    label: string;
    /**
     * The URL or path the link points to. Use a relative path, anchor or full http(s), mailto or tel URL.
     */
    href: string;
    /**
     * Whether the link should open in a new tab.
     */
    newTab?: boolean | null;
    id?: string | null;
  }[];
  landAcknowledgement: {
    title: string;
    body: string;
  };
  attribution: string;
  socialLinks: {
    /**
     * The text to display for the link.
     */
    label: string;
    /**
     * The URL or path the link points to. Use a relative path, anchor or full http(s), mailto or tel URL.
     */
    href: string;
    /**
     * Whether the link should open in a new tab.
     */
    newTab?: boolean | null;
    id?: string | null;
  }[];
  newsletter: {
    /**
     * Heading for the newsletter signup form.
     */
    label: string;
    /**
     * Placeholder text for the newsletter signup input.
     */
    placeholder: string;
    /**
     * Message shown to the user after successfully signing up for the newsletter.
     */
    successMessage: string;
    /**
     * Message shown to the user if there is an error signing up for the newsletter.
     */
    errorMessage: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls home page content managed by Payload.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Controls the introductory headline, actions and image mosaic on the home page.
   */
  hero?: {
    /**
     * The main headline text for the hero section.
     */
    title?: string | null;
    /**
     * A smaller headline that appears below the main title.
     */
    subtitle?: string | null;
    /**
     * Additional descriptive text that appears below the title and subtitle.
     */
    description?: string | null;
    /**
     * The main call-to-action for this hero. This should be the most important action you want users to take.
     */
    primaryAction?: {
      /**
       * The text to display for this action.
       */
      label?: string | null;
      /**
       * The URL or path this action links to. Use a relative path, anchor or full http(s).
       */
      href?: string | null;
      /**
       * Whether this link should open in a new browser tab.
       */
      newTab?: boolean | null;
    };
    /**
     * An optional secondary action. This can be used for a less prominent link, such as to a contact page or external resource.
     */
    secondaryAction?: {
      enabled?: boolean | null;
      /**
       * The text to display for this action.
       */
      label?: string | null;
      /**
       * The URL or path this action links to. Use a relative path, anchor or full http(s).
       */
      href?: string | null;
      /**
       * Whether this link should open in a new browser tab.
       */
      newTab?: boolean | null;
    };
    /**
     * Add up to five images. The layout uses them from left to right, then falls back to quiet placeholders for empty slots.
     */
    images?:
      | {
          image: number | Media;
          /**
           * Optional alt text override. Leave empty to use the media alt text.
           */
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Controls the about section that appears below the home page hero.
   */
  about?: {
    /**
     * The headline for the about section.
     */
    heading?: string | null;
    /**
     * Main about copy. Use rich text for links and simple emphasis; keep headings out because the section already has a headline.
     */
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * The link displayed below the about copy.
     */
    action?: {
      /**
       * The text to display for this action.
       */
      label?: string | null;
      /**
       * The URL or path this action links to. Use a relative path, anchor or full http(s).
       */
      href?: string | null;
      /**
       * Whether this link should open in a new browser tab.
       */
      newTab?: boolean | null;
    };
    /**
     * Optional image displayed below the about copy. A neutral placeholder appears when empty.
     */
    image?: (number | null) | Media;
    /**
     * Optional alt text override. Leave empty to use the media alt text.
     */
    imageAlt?: string | null;
  };
  /**
   * Controls the copy and link for the home page featured projects section. Featured project cards are pulled from the Projects collection.
   */
  featuredProjects?: {
    /**
     * The headline for the featured projects section.
     */
    heading?: string | null;
    /**
     * Introductory copy displayed above the project cards.
     */
    description?: string | null;
    /**
     * Choose up to five projects for the home page. Drag rows to control display order.
     */
    projects?:
      | {
          /**
           * Project to display in this featured slot.
           */
          project: number | Project;
          id?: string | null;
        }[]
      | null;
    /**
     * The link displayed below the featured projects copy.
     */
    action?: {
      /**
       * The text to display for this action.
       */
      label?: string | null;
      /**
       * The URL or path this action links to. Use a relative path, anchor or full http(s).
       */
      href?: string | null;
      /**
       * Whether this link should open in a new browser tab.
       */
      newTab?: boolean | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  contactLink?:
    | T
    | {
        enabled?: T;
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  primaryNavigationTitle?: T;
  primaryNavigationItems?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  projectNavigationTitle?: T;
  projectNavigationItems?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  landAcknowledgement?:
    | T
    | {
        title?: T;
        body?: T;
      };
  attribution?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  newsletter?:
    | T
    | {
        label?: T;
        placeholder?: T;
        successMessage?: T;
        errorMessage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
        primaryAction?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
            };
        secondaryAction?:
          | T
          | {
              enabled?: T;
              label?: T;
              href?: T;
              newTab?: T;
            };
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        heading?: T;
        body?: T;
        action?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
            };
        image?: T;
        imageAlt?: T;
      };
  featuredProjects?:
    | T
    | {
        heading?: T;
        description?: T;
        projects?:
          | T
          | {
              project?: T;
              id?: T;
            };
        action?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}